"""Default options and covariance labels for the SARIMAX implementation."""

from __future__ import absolute_import, print_function

DEFAULT_SARIMAX_COV_TYPE = 'opg'
COV_TYPE_APPROX = 'approx'
COV_TYPE_OPG = 'opg'
COV_TYPE_ROBUST_APPROX = 'robust_approx'
COV_TYPE_NONE = 'none'

ARIMA_COV_TYPES = [COV_TYPE_OPG, COV_TYPE_APPROX, COV_TYPE_ROBUST_APPROX, COV_TYPE_NONE]

DEFAULT_SARIMAX_GTOL = 1e-4
DEFAULT_SARIMAX_XTOL = 1e-6
DEFAULT_SARIMAX_FTOL = 1e-12

DEFAULT_SARIMAX_MAXITER = 100

DEFAULT_SARIMAX_STEADY_STATE_TOL = 1e-8

DEFAULT_SARIMAX_BFGS_B0 = 100.0

DEFAULT_SARIMAX_ENFORCE_STATIONARITY = False
DEFAULT_SARIMAX_ENFORCE_INVERTIBILITY = False
DEFAULT_SARIMAX_DO_HANNAN_RISSANEN = True

DEFAULT_SARIMAX_INITIAL_DIFFUSE_VARIANCE = 1e6

DEFAULT_SARIMAX_CONCENTRATE_SCALE = False

DEFAULT_SARIMAX_SIMPLE_DIFFERENCING = True  # Difference before Kalman filtering by default.

DEFAULT_SARIMAX_MULTIPLICATIVE = False  # The fit path raises if multiplicative=True.

DEFAULT_SARIMAX_DIFFUSE = False  # DOESN'T MAKE SENSE TO BE TRUE...

DEFAULT_SARIMAX_STANDARDIZE_ENDOG = True  # Stabilizes optimization, then parameters are rescaled.
