from __future__ import absolute_import, print_function

import numpy as np


BOOTSTRAP = 'BOOTSTRAP'
SANDWICH = 'SANDWICH'
CLUSTER = 'CLUSTER'

GMM_COV_TYPES = [BOOTSTRAP, SANDWICH, CLUSTER]
DEFAULT_GMM_COV_TYPE = SANDWICH

EPS = np.finfo(float).eps

DEFAULT_GMM_BOOTSTRAP_N_SAMPLES = 100

DEFAULT_GMM_USE_T = True
DEFAULT_GMM_TEST_LEVEL = .05

DEFAULT_GMM_MAX_ITER = 100

DEFAULT_GMM_X_TOL = EPS ** .5
DEFAULT_GMM_G_TOL = EPS ** .5
DEFAULT_GMM_F_TOL = EPS ** .5

DEFAULT_GMM_DELTA = None

ONE_STEP = 'ONE_STEP'
TWO_STEP = 'TWO_STEP'
ITERATIVE = 'ITERATIVE'

DEFAULT_GMM_METHOD = TWO_STEP

GMM_METHODS = [ITERATIVE, ONE_STEP, TWO_STEP]

DEFAULT_ITERATIVE_GMM_MAX_ITER = 10
DEFAULT_ITERATIVE_GMM_X_TOL = EPS ** .5

GMM_GENERAL = 'GENERAL'
GMM_IV_LINEAR = 'IV_LINEAR'
GMM_IV_NONLINEAR = 'IV_NONLINEAR'
GMM_MLE = 'MLE'
GMM_GLM = 'GLM'

GMM_MODEL_TYPES = [GMM_GENERAL, GMM_IV_LINEAR, GMM_IV_NONLINEAR,
                   GMM_MLE, GMM_GLM]
